### ISSUE TITLE
Fix L_eff calculation to make it more generalized to arbitrary lengths/configurations

### ISSUE THREAD

**Issue by jcchin** [jcchin/boring#36]
Need to also ask if L_eff is different than L_total

L_eff may be center-to-center
L_total would be end-to-end of cells

**Comment by sschnulo** [comment]
Daisy chain axial resistances

**Comment by sschnulo** [comment]
@sschnulo

**Comment by jcchin** [comment]
L_adiabatic is also going to be calculated in an upstream component based on the insulation thickness (this connection doesn't exist yet)

L_eff = L_adiabatic is wrong in `axial_thermal_resistance`, this is probably where some of the confusion came from @sschnulo
