### ISSUE TITLE
Insulation Mass Estimate

### ISSUE THREAD

**Issue by jcchin** [jcchin/boring#38]

**Comment by jcchin** [comment]
@dlhall04

**Comment by jcchin** [comment]
inputs:
num_cells
thickness `d`
cell dimensions (L*W*H)
aerogel_props

outputs:
volume/area_{insulation} <-- we need to know this intermediate value so we can order it
mass_{insulation}


thickness (d) is currently calculated using tempODE inside `sizing/structure.py` and `geometry/calcthickness.py`

**Comment by dlhall04** [comment]
Posted the PR with the insulation mass component along with it's component test. All derivatives are left as CS for now.
